# Generated by Django 5.0.4 on 2026-10-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=150, verbose_name="Título")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("ambiental", "Ambiental"),
                            ("social", "Social"),
                            ("governanca", "Governança"),
                        ],
                        default="ambiental",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aguardando", "Aguardando início"),
                            ("andamento", "Em andamento"),
                            ("concluido", "Concluído"),
                        ],
                        default="aguardando",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
            ],
            options={
                "verbose_name": "Atividade",
                "verbose_name_plural": "Atividades",
                "ordering": ["data_criacao"],
            },
        ),
    ]
