# Generated by Django 4.2.30 on 2026-09-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('assunto', models.CharField(choices=[('bug', 'Reportar um bug'), ('sugestao', 'Sugestão'), ('duvida', 'Dúvida'), ('outro', 'Outro')], default='outro', max_length=20, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Recebida em')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida')),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
