# Generated by Django 6.1.1 on 2026-09-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=150, verbose_name='Nome da Empresa')),
                ('residuos_textesis', models.BooleanField(default=False, verbose_name='Faz gestão de resíduos têxteis?')),
                ('energia_renovavel', models.BooleanField(default=False, verbose_name='Utiliza energia renovável?')),
                ('condicoes_trabalho', models.BooleanField(default=False, verbose_name='Garante boas condições de trabalho?')),
                ('diversidade_inclusao', models.BooleanField(default=False, verbose_name='Possui políticas de diversidade?')),
                ('rastreabilidade', models.BooleanField(default=False, verbose_name='Tem rastreabilidade de fornecedores?')),
                ('codigo_etica', models.BooleanField(default=False, verbose_name='Possui Código de Ética?')),
            ],
        ),
    ]
