# Generated by Django 6.1.1 on 2026-09-22 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticoesg',
            name='combate_corrupcao',
            field=models.BooleanField(default=False, verbose_name='Possui políticas formais de anticorrupção ou canal de denúncias?'),
        ),
        migrations.AddField(
            model_name='diagnosticoesg',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnosticoesg',
            name='materias_sustentaveis',
            field=models.BooleanField(default=False, verbose_name='Utiliza matérias-primas orgânicas, recicladas ou certificadas?'),
        ),
        migrations.AddField(
            model_name='diagnosticoesg',
            name='saude_seguranca',
            field=models.BooleanField(default=False, verbose_name='Oferece programas formais de saúde, segurança no trabalho e ergonomia?'),
        ),
        migrations.AddField(
            model_name='diagnosticoesg',
            name='transparencia_fiscal',
            field=models.BooleanField(default=False, verbose_name='Mantém transparência total em obrigações fiscais, jurídicas e relatórios?'),
        ),
        migrations.AddField(
            model_name='diagnosticoesg',
            name='treinamento_equipe',
            field=models.BooleanField(default=False, verbose_name='Promove treinamentos e capacitação contínua para os colaboradores?'),
        ),
        migrations.AddField(
            model_name='diagnosticoesg',
            name='uso_agua',
            field=models.BooleanField(default=False, verbose_name='Possui processos para medição e redução do consumo de água?'),
        ),
        migrations.AlterField(
            model_name='diagnosticoesg',
            name='codigo_etica',
            field=models.BooleanField(default=False, verbose_name='Possui um Código de Ética e Conduta formalizado e acessível a todos?'),
        ),
        migrations.AlterField(
            model_name='diagnosticoesg',
            name='condicoes_trabalho',
            field=models.BooleanField(default=False, verbose_name='Garante condições de trabalho seguras, salários justos e apoio à comunidade local?'),
        ),
        migrations.AlterField(
            model_name='diagnosticoesg',
            name='diversidade_inclusao',
            field=models.BooleanField(default=False, verbose_name='Possui políticas ativas de diversidade, inclusão e equidade de gênero?'),
        ),
        migrations.AlterField(
            model_name='diagnosticoesg',
            name='energia_renovavel',
            field=models.BooleanField(default=False, verbose_name='Utiliza fontes de energia renovável ou eficiência energética na produção?'),
        ),
        migrations.AlterField(
            model_name='diagnosticoesg',
            name='nome_empresa',
            field=models.CharField(max_length=150, verbose_name='Nome da Empresa / Confecção'),
        ),
        migrations.AlterField(
            model_name='diagnosticoesg',
            name='rastreabilidade',
            field=models.BooleanField(default=False, verbose_name='Possui rastreabilidade e controle sobre a origem dos fornecedores de matéria-prima?'),
        ),
        migrations.AlterField(
            model_name='diagnosticoesg',
            name='residuos_textesis',
            field=models.BooleanField(default=False, verbose_name='Realiza a gestão ou reciclagem de resíduos têxteis e sobras de corte?'),
        ),
    ]
